steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/zonappz/chatgpt-agi', '-f', 'Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/zonappz/chatgpt-agi']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'chatgpt-agi', '--image', 'gcr.io/zonappz/chatgpt-agi', '--platform', 'managed', '--region', 'us-central1']
